---
- name: install docker and nginx
  hosts: all
  become: yes
  tasks:
    - name: install packages
      package:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present
      when: ansible_distribution == "RedHat"
